# Generated by Django 4.1.3 on 2022-11-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pic')),
                ('descrip', models.TextField(max_length=100)),
            ],
        ),
    ]
